### ISSUE TITLE
run program on host using bashoperator

### ISSUE THREAD

**Issue by krishna61834** [datarods/docker-airflow#3]
Hi ,

My task has below code for bashoperator.

dbt_t1 = BashOperator(task_id="dbt_deps", bash_command="cd /Users/userid/project_dbt && wxdbt deps")

wxdbt deps is a programm which should run inside host directory /Users/userid/project_dbt and it uses host userid and password.

task is failing with below error in webserver(UI) :
[2019-11-08 07:37:52,780] {{bash_operator.py:128}} INFO - /tmp/airflowtmpqipl33d9/dbt_depsqs_1dean: line 1: cd: /Users/userid/project_dbt: No such file or directory

so in nutshell the requirement is to run program on host machine which uses host userid and password using bashoperator .

Can you please provide some solution for it.?

Thanks in advance.
--Krishna

**Comment by impredicative** [comment]
Containerized Aiflow implicitly restricts and prohibits access to the host.

If it helps, you can mount the host directory into the Airflow container using a volume mount via a `Dockerfile` or `docker run` or `docker-compose.yml`. Refer to the respective docs for it.

Alternatively, you will have to create or use a Docker image of `dbt` and run that using thr Docker operator or such. I would do it this way.

**Comment by krishna61834** [comment]
Thanks a lot impredicative.
Somewhere I read below solution to  'run shell script on host from docker container'?. What do you say.??
ssh -l ${USERNAME} ${HOSTNAME} "${SCRIPT}"

**Comment by impredicative** [comment]
I recommend keeping your solutions dockerized as it maximizes reproducibility.

Yes, you can alternatively go the shell script route, but it's a not a scalable approach for when you have dozens of jobs to simultaneously run. A more scalable approach is more likely to use reproducible containers that can run across multiple hosts. There are no hard rules though.

**Comment by krishna61834** [comment]
Thanks a lot !!. Really appreciate it for your valuable suggestions!!
